version: '3'
volumes:
  dados:
services:
  db:
    image: postgres:9.6
    volumes:
      # data volume
      - dados:/var/lib/postgresql/data
      #SCRPITS mapping the local scripts path to the container scripts path
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

      


