version: '3'
volumes:
  dados:
networks:
  banco:
  web:
services:
  db:
    image: postgres:9.6
    volumes:
      # data volume
      - dados:/var/lib/postgresql/data
      #SCRPITS mapping the local scripts path to the container scripts path
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - banco
  frontend:
    image: nginx:1.13
    volumes:
      #site
      - ./web:/usr/share/nginx/html/
      #config reverse proxy
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
        #create a depedency with app service (starts executing a service with no dependency and automatically start a a dependency service)
    depends_on:
      - app
  app:
    image: python:3.6
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks:
      - web
      - banco
    depends_on:
      - db
      
      


